name = "ParallelKMeans"
uuid = "42b8e9d4-006b-409a-8472-7f34b3fb58af"
authors = ["Bernard Brenyah", "Andrey Oskin"]
version = "0.1.0"

[deps]
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
StatsBase = "0.32, 0.33"
julia = "1.3"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"

[targets]
test = ["Test", "Random", "Suppressor", "MLJBase"]
